### ISSUE TITLE
More sample code

### ISSUE THREAD

**Issue by Hansanshi** [light-tech/MiniGit#3]
Hi

first of all, I'm not familiar with Swift. I just want try some idea.

The [official sample ](https://github.com/light-tech/MiniGit-SampleApp) is little simple to how to use.

Could you please provide more sample code?

**Comment by light-tech** [comment]
Well, the sample (purposely made simple) is intended to give you the template for most things you want to do with the library. Git has many use cases, can you be more specific what you want to do? You might want to learn not just Swift but [SwiftUI](https://developer.apple.com/tutorials/swiftui) as well since the library is designed to work with SwiftUI; in particular, to provide _data models_ (Git repository, the result of git status, ...) for YOUR views. (See MVC or MVVM UI design patterns.) In the sample, the [ContentView](https://github.com/light-tech/MiniGit-SampleApp/blob/main/MiniGitSample/ContentView.swift) provides the view that reflects the current state of the repository:
 * If cloning is in progress, show a `ProgressView`
 * Show the commit history, if the repository exists

**Comment by Hansanshi** [comment]
I want to use git to sync text file with remote repo, so  git pull, push and merge will be the main commands.

**Comment by light-tech** [comment]
This is doable at the moment (the functionality is there) but a couple of changes to the library might make it easier. That is because the library was currently designed for users to operate via GUI. For example, if you are using git command line like
```shell
git push origin master
```
you have to tell `git push` two pieces of information: the remote repo (`origin` in this case) and the branch to push the changes to (`master`). The alternative command
```shell
git push origin --all
```
will push all changes to preconfigured push [refspecs](https://git-scm.com/book/en/v2/Git-Internals-The-Refspec). But you still need to tell the remote repo to push to.

In the GUI application, the user can tap on the desired remote to push. Your use case is like doing it without the user intervention. Currently for pushing, you could do something like
```
let allRemotes = repo.getRemotes()     // get the list of remotes
let remoteOrigin = allRemotes[0]         // assuming you have only one remote i.e. origin
repo.push(remoteOrigin)                      // push all branches to the corresponding one in origin
```
A pull is just a fetch followed by merge. Fetch is trivial
```
repo.fetch(remoteOrigin)
```
(One unfortunate thing is that this will do things in background and we do not supply a callbacks at the moment. So you won't know when the fetch completes to do the merge. The library really needs some design improvement.)

But a merge usually requires user intervention in case there are conflicts. If you are sure that there is no conflict, then to merge you need a [reference](https://git-scm.com/book/en/v2/Git-Internals-Git-References) such as `master` (what you want to merge into the current branch). With the current GUI-oriented design, the list of all references is hidden inside the commits in the commit graph (git log).
```
repo.updateCommitGraph()
for c in  repo.commitGraph.commits {
    for ref in c.refs {
        if ref.name == "refs/remotes/origin/master" {
             repo.merge([ref])    // merge the changes in the remote repo "origin/master" into the local "master"
        }
    }
}
```

**Comment by light-tech** [comment]
Push/fetch/merge added to the sample app at https://github.com/light-tech/MiniGit-SampleApp/commit/905e01914ee21ae736d4d0ac5c4971b3831ae036

**Comment by Hansanshi** [comment]
thanks
