### ISSUE TITLE
M1 support?

### ISSUE THREAD

**Issue by i-tengfei** [light-tech/MiniGit#4]
Will M1 be supported in the future?
I'd like to help make it support M1, but don't know how to start.

**Comment by light-tech** [comment]
The only reason M1 could not be supported is because we do not have an M1 Mac to test it.

Basically, you just need to build libgit2 XCFramework on an M1 Mac (mainly for Simulator and Mac Catalyst), for example, using our script at https://github.com/light-tech/LibGit2-On-iOS/. (It was already set up to build on M1.)

Then upload the `libgit2.xcframework.zip` somewhere and change the URL and checksum in the [`Package.swift`](https://github.com/light-tech/MiniGit/blob/main/Package.swift) or simply use your XCFramework locally by changing the declaration to
```swift
.binaryTarget(
            name: "libgit2",
            path: "RELATIVE_PATH_TO_YOUR_XCFRAMEWORK")
```
And you are good to go.

Eventually, we will release only M1 version of the package.

**Comment by light-tech** [comment]
We are closing this as our build scripts can now support M1 as well, as of [this commit](https://github.com/light-tech/MiniGit/commit/65e0f7f3691504e2a4f1073cc8b7954f84c5c08f).
